apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: matchbook
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: matchbook
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: websocket
      port: 81
      targetPort: websocket
      protocol: TCP
