apiVersion: v1
kind: Service
metadata:
  name: crank
  namespace: matchbook
  labels:
    app.kubernetes.io/name: crank
    app.kubernetes.io/component: crank
    app.kubernetes.io/part-of: matchbook
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: crank
    app.kubernetes.io/component: crank
  ports:
    - name: metrics
      port: 9091
      targetPort: metrics
      protocol: TCP
