apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matchbook-services
  namespace: matchbook
  labels:
    app.kubernetes.io/name: matchbook
    app.kubernetes.io/part-of: matchbook
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: matchbook
  namespaceSelector:
    matchNames:
      - matchbook
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matchbook-api
  namespace: matchbook
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: matchbook
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  namespaceSelector:
    matchNames:
      - matchbook
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
