apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matchbook-dev

resources:
  - ../../base

nameSuffix: -dev

patches:
  - path: configmap-patch.yaml
  - path: replicas-patch.yaml

secretGenerator:
  - name: matchbook-secrets
    behavior: replace
    files:
      - secrets.env

images:
  - name: ghcr.io/joaquinbejar/matchbook-indexer
    newTag: dev
  - name: ghcr.io/joaquinbejar/matchbook-api
    newTag: dev
  - name: ghcr.io/joaquinbejar/matchbook-crank
    newTag: dev
